version: '3'

services:
  #db not included because its hosted on AWS (for sharing and easy showcasing) - if you want to feel free to add a MySQL DB here and set config vars in application-prod.properties

  myapp-main:
    build:
      .
    restart: on-failure
    ports:
      - 8090:8090
    environment:
      - PORT=8090