version: '3'

services:

  cooltimedia-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cooltimediadb
      - MYSQL_USER=cooltimedia
      - MYSQL_PASSWORD=pass1234

  myapp-main:
    build:
      .
    restart: on-failure
    depends_on:
      - cooltimedia-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=cooltimedia-db
      - DATABASE_USER=cooltimedia
      - DATABASE_PASSWORD=pass1234
      - DATABASE_NAME=cooltimediadb
      - DATABASE_PORT=3333